[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "translator_nodes"
version = "0.1.0"
description = "Translator Nodes Package"
requires-python = ">=3.8"

[tool.setuptools.packages.find]
include = ["translator*"]
